version: "3"

services:
  web:
    build: ./
    env_file:
      - ./.web.dev.env
    depends_on:
      - db
    volumes:
      - static:/static/
  db:
    image: mysql:5.7
    command: >-
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_USER=blog
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=654321
    volumes:
      - database:/var/lib/mysql
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static/
    depends_on:
      - web

volumes:
  database:
  static:

