# Generated by Django 2.2.17 on 2020-11-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='code_class',
            field=models.CharField(default='plaintext', max_length=10, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='paste',
            name='valid_day',
            field=models.IntegerField(default=3, verbose_name='有效时间'),
        ),
    ]
