# Generated by Django 2.2.17 on 2020-11-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0002_auto_20201120_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='code_class',
            field=models.CharField(default='nohighlight', max_length=15, verbose_name='语言'),
        ),
    ]
