# Generated by Django 2.2.9 on 2020-01-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_audit',
            field=models.BooleanField(default=True, verbose_name='审核'),
        ),
    ]
