# Generated by Django 2.2.9 on 2020-01-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_contact_is_audit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-publish_time'], 'verbose_name': '留言', 'verbose_name_plural': '留言'},
        ),
    ]
