# Generated by Django 2.2.9 on 2020-01-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_auto_20200116_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_audit',
            field=models.BooleanField(default=False, verbose_name='审核'),
        ),
    ]
