# Generated by Django 2.2.9 on 2020-01-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_auto_20200116_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='主题'),
        ),
    ]
