# Generated by Django 2.2.17 on 2021-01-06 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_auto_20200116_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='时间'),
            preserve_default=False,
        ),
    ]
